# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
    ]
