# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0002_auto_20170823_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_author',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
