# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0005_auto_20170823_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_price',
            field=models.IntegerField(default=100, verbose_name='Цена'),
        ),
    ]
