# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0008_auto_20170823_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
