# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0009_auto_20170823_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lot_text',
            field=models.TextField(default=1, max_length=200, verbose_name='Описание лота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_last_bet',
            field=models.IntegerField(default=0, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_price',
            field=models.BigIntegerField(verbose_name='Цена'),
        ),
    ]
