# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0010_auto_20170824_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lot_bool',
            field=models.BooleanField(default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
