# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0013_auto_20170824_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lot_status',
            field=models.CharField(default=1, max_length=20, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
