# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0014_lot_lot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_created_date',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lot_status',
        ),
    ]
