# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0015_auto_20170824_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_bool',
            field=models.BooleanField(default=False, verbose_name='Значение статуса'),
        ),
    ]
