# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0017_auto_20170824_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_bool',
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_status',
            field=models.BooleanField(choices=[(True, 'Активный'), (False, 'Завершенный')], default=True, verbose_name='Статус'),
        ),
    ]
