# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotAPP', '0018_auto_20170824_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_sum', models.IntegerField(default=0, verbose_name='Сумма ставки')),
                ('bet_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор ставки')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
            },
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lot_last_bet',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_on_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotAPP.Lot', verbose_name='Выберите лот для ставки'),
        ),
    ]
