# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotAPP', '0019_auto_20170824_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_sum',
            field=models.IntegerField(verbose_name='Сумма ставки'),
        ),
    ]
